services:
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile.dev
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./services/client:/app
      - /app/.next
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_SERVER_API_URL=http://core-api:3001
      - WATCHPACK_POLLING=true

  core-api:
    build:
      context: ./services/core-api
      dockerfile: Dockerfile.dev
    ports:
      - "${API_PORT}:${API_PORT}"
    develop:
      watch:
        - action: sync+restart
          path: ./services/core-api
          target: /app
    volumes:
      - ./services/core-api:/app
      - /app/node_modules
    # env_file:
    # - ./services/core-api/.env
    # - .env
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - API_SECRET_KEY=${API_SECRET_KEY}
    command: npm run dev

  docs:
    build:
      context: ./services/docs
      dockerfile: Dockerfile.dev
    ports:
      - "${DOCS_PORT}:${DOCS_PORT}"
    volumes:
      - ./services/docs:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev -- --port 3002 --host

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
